# Despliegue: Predicción para datos futuros

#1. Cargamos el modelo
#2. Cargamos los datos futuros
#3. Cargamos los datos futuros
#4. Aplicamos el modelo para la predicción

**#1. Cargamos el modelo**

In [ ]:
# Cargamos el modelo
import pickle
filename = 'modeloVideojuegos.pkl'
model_Tree, model_Knn, variables = pickle.load(open(filename, 'rb'))

In [ ]:
# Cargamos los datos futuros
data = pd.read_csv('videojuegos-datosFuturos.csv')
data.head()

         videojuego  Edad    Sexo      Plataforma  Consumidor_habitual
0     'Mass Effect'    33  Hombre           Otros                False
1  'KOA: Reckoning'    30   Mujer              PC                 True
2      'Dead Space'    22  Hombre          'Xbox'                False
3          'Crysis'    17  Hombre  'Play Station'                False
4        'Sim City'    27   Mujer           Otros                 True

In [ ]:
# Creamos variables dummy para convertir la categoría a números
data_preparada = data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['videojuego', 'Plataforma'], drop_first=False, dtype=int)
data_preparada = pd.get_dummies(data_preparada, columns=['Sexo', 'Consumidor_habitual'], drop_first=False, dtype=int)
data_preparada.head()

,Edad,videojuego_'Crysis',videojuego_'Dead Space',videojuego_'KOA: Reckoning',videojuego_'Mass Effect',videojuego_'Sim City',Plataforma_'Play Station',Plataforma_'Xbox',Plataforma_Otros,Plataforma_PC,Sexo_Hombre,Sexo_Mujer,Consumidor_habitual_False,Consumidor_habitual_True
0,33,0,0,0,1,0,0,0,1,0,1,0,1,0
1,30,0,0,1,0,0,0,0,0,1,0,1,0,1
2,22,0,1,0,0,0,0,1,0,0,1,0,1,0
3,17,1,0,0,0,0,1,0,0,0,1,0,1,0
4,27,0,0,0,0,1,0,0,1,0,0,1,0,1

In [ ]:
# Se adicionan la scolumnas faltantes
data_preparada = data_preparada.reindex(columns = variables, fill_value=0)
data_preparada.head()

,Edad,videojuego_'Battlefield',videojuego_'Crysis',videojuego_'Dead Space',videojuego_'F1',videojuego_'Fifa',videojuego_'KOA: Reckoning',videojuego_'Mass Effect',videojuego_'Sim City',Plataforma_'Play Station',Plataforma_'Xbox',Plataforma_Otros,Plataforma_PC,Sexo_Mujer,Consumidor_habitual_True
0,33,0,0,0,0,0,0,1,0,0,0,1,0,0,0
1,30,0,0,0,0,0,1,0,0,0,0,0,1,1,1
2,22,0,0,1,0,0,0,0,0,0,1,0,0,0,0
3,17,0,1,0,0,0,0,0,0,1,0,0,0,0,0
4,27,0,0,0,0,0,0,0,1,0,0,1,0,1,1

**4. Predicción**

In [ ]:
# Hacemos la predicción con Tree
Y_fut = model_Tree.predict(data_preparada)
Y_fut

array([ 20., 200., 200., 300., 600.])

In [ ]:
data['Prediccion_Tree']= Y_fut
data

,videojuego,Edad,Sexo,Plataforma,Consumidor_habitual,Prediccion_Tree
0,'Mass Effect',33,Hombre,Otros,False,20.0
1,'KOA: Reckoning',30,Mujer,PC,True,200.0
2,'Dead Space',22,Hombre,'Xbox',False,200.0
3,'Crysis',17,Hombre,'Play Station',False,300.0
4,'Sim City',27,Mujer,Otros,True,600.0

In [ ]:
#Hacemos la predicción con Knn
Y_knn = model_Knn.predict(data_preparada)
Y_knn

array([ 20., 100., 200., 300., 600.])

In [ ]:
data['prediccion_Knn']= Y_knn
data

,videojuego,Edad,Sexo,Plataforma,Consumidor_habitual,Prediccion_Tree,prediccion_Knn
0,'Mass Effect',33,Hombre,Otros,False,20.0,20.0
1,'KOA: Reckoning',30,Mujer,PC,True,200.0,100.0
2,'Dead Space',22,Hombre,'Xbox',False,200.0,200.0
3,'Crysis',17,Hombre,'Play Station',False,300.0,300.0
4,'Sim City',27,Mujer,Otros,True,600.0,600.0